design:
  next:
    - coding
  config: agent.yaml
  agent:
    name: LLMAgent
    kwargs:
      tag: Architecture

coding:
  next:
    - human_eval
  agent:
    name: CodeAgent
    kwargs:
      code_file: codes/coding
      tag: Coding


human_eval:
  agent:
    name: LLMAgent
    kwargs:
      tag: HumanEvalRefiner