coding:
  next:
    - evaluate
  config: coding.yaml
  engine:
    name: SimpleEngine
    kwargs:
      trust_remote_code: true

evaluate:
  next:
    - remove_arch_review
  engine:
    name: CodeEngine
    kwargs:
      code_file: code_review

remove_arch_review:
  next:
    - refine
  engine:
    name: CodeEngine
    kwargs:
      code_file: remove_arch_review

refine:
  next:
    - add_human_eval
  engine:
    name: SimpleEngine
    kwargs:
      trust_remote_code: true

add_human_eval:
  next:
    - human_eval
  engine:
    name: CodeEngine
    kwargs:
      code_file: add_human_eval


human_eval:
  engine:
    name: SimpleEngine
    kwargs:
      trust_remote_code: true
